# -*- coding: utf-8 -*-
"""StreamlitApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWsw0VHkPvHHgu9_47JNbIrIEeUWHnz8

# Deploy on Streamlit
"""

!pip install streamlit tensorflow  # or torch, depending on your framework

import streamlit as st
from PIL import Image
import numpy as np
import tensorflow as tf

# Load the pre-trained model
model = tf.keras.models.load_model('Cat_dog_model.h5')

# Define the Streamlit app
st.title('Image Prediction Model Deployment with Streamlit')

# Collect user input: Image upload
st.header('Upload an Image')
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded Image.', use_column_width=True)

    # Make prediction
    if st.button('Predict'):
        result = predict_image(image)
        st.write(f'Prediction: {result}')