# -*- coding: utf-8 -*-
"""Car Rental App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12RIj2mkagSJ4A-bRBuqAUeoDgvg0oHjY
"""

from car_rental import car_rent
from customer import customer
from datetime import datetime

def main():
    """
    Main function to run the program.
    """
    print("Welcome to Car Rental")
    car_rental_instance = car_rent(10)

    while True:
        print("Select available options:\n1. Display Car\n2. Rent Car\n3. Return Car\n4. Exit")

        choice = int(input("Enter your choice: "))
        if choice == 1:
            car_rental_instance.display_car()
        elif choice == 2:
            name = input("Enter your name: ")
            customer_instance = customer(name)
            rental_units = int(input("Enter the number of units to be rented: "))
            try:
                rental_mode = input("Enter the rental mode (hourly/daily/weekly): ")
                if rental_mode not in ["hourly", "daily", "weekly"]:
                    print("Invalid rental mode. Please enter 'hourly', 'daily', or 'weekly'.")
                    continue
            except ValueError:
                    print("Invalid input. Please enter a number for rental units.")
                    continue
            customer_instance.request_car(car_rental_instance, rental_units, rental_mode)
        elif choice == 3:
            name = input("Enter your name: ")
            customer_instance = customer(name)
            rental_units = int(input("Enter the number of units to be returned: "))
            customer_instance.return_car(car_rental_instance, rental_units)
        elif choice==4:
            print("Exiting the program.")
            break
        else:
            print("Invalid choice")
            continue

if __name__ == "__main__":
    main()

