# -*- coding: utf-8 -*-
"""Customer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kB-7P8-DKx3FgUhfn0cbRoG4w1jF_9Gs
"""

class customer:
  def __init__(self,name):
    self.name=name
  def request_car(self,car_rental_instance,rental_units,rental_mode):
     return car_rental_instance.rent_car(rental_units,rental_mode)
  def return_car(self,car_rental_instance,rental_units):
     return car_rental_instance.return_car(rental_units)